### PR TITLE
Spanish strings

### PR DESCRIPTION
**Pull request by 3DOeste**
I tried to translate the strings with words one would expect from a machine in certain cases.

### CODE REVIEW

**Comment by dc42** [comment]
Thanks! the "n/a" string stands for "not available". It is used in place of the estimated time until the print completes, when there are no estimates available. It can be only a few characters long.

**Comment by dc42** [comment]
PS - the "low voltage" string should now be the translation of "Standby". It is the printer state displayed when there is 5V power to the Duet but no VIN power.

**Comment by 3DOeste** [comment]
Ok David, I changed those strings. Let me know if there are other changes needed!

**Comment by dc42** [comment]
Thanks very much!

**Comment by 3DOeste** [comment]
You're welcome! I'm glad I could help with something!

**Comment by 3DOeste** [comment]
Hi David, there's no problem. I've translated the missing strings. Let me know if you need something else.

PS - I just realized the Czech translation... If "fijar" is too long, "OK" could be perfectly used. Sorry I missed that part of your message.

**Pull request merged**
